### ISSUE TITLE
Account for mono (1-channel) input

### ISSUE THREAD

**Issue by Catsvilles** [khoin/DattorroReverbNode#2]
Hi! The library seems awesome but for some reasons, I get this error:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at AudioWorkletProcessor.process (dattorroReverb.js:215)
```

I connect it with Tone.js Player and OfflineAudioContext. Here is the example of what I'm doing (assuming async function):

```
  await offlineContext.audioWorklet.addModule('./plugins/DattorroReverbNode/dattorroReverb.js');
  let reverb = new AudioWorkletNode(offlineContext, 'DattorroReverb');
```

I will appreciate if you have some quick fix, if not I will try to investigate, get more details and maybe find a fix. Thank you! :)

**Comment by khoin** [comment]
I suspect it is because the input into the module is mono. In fact, this should be taken account, as the Dattorro design mixes the stereo signal to mono before processing. Right now, you can simply turn your mono input into stereo before connecting.

**Comment by Catsvilles** [comment]
@khoin Hm, unfortunately, this cannot be the issue as I have never used mono, I always use stereo in most of the cases. I will try to dive deeper in one of those days. :)

**Comment by khoin** [comment]
If you could provide the code to reproduce the error, that would be great. Thanks!

**Comment by khoin** [comment]
Hi there @Catsvilles I wonder if you could check in and see if the problem still persists? Thank you so much!

**Comment by Catsvilles** [comment]
@khoin Yes, I still receive this error in console. Sorry, it takes and will take me more of time to investigate this error, also I believe even though the error is thrown the reverb is still applied to my AudioBuffer, so yeah, it kind of works anyway. I will investigate more, asap.
Here are few more details on how I'm using DattorroReverbNode, in case someone will want to reproduce, maybe these things affect it somehow:
1. I use it in forEach loop to process multiple AudioBuffers at the same time with OfflineContext. The error in NOT thrown when using just one AudioBuffer outside of loop, I happen to catch this error only in forEach loop.
2. I always use stereo samples.

**Comment by rikard-io** [comment]
Had the same issue. Resolved it by explicitly specifying  outputChannelCount, so 
`new AudioWorkletNode(waContext, 'DattorroReverb', {
			outputChannelCount: [2],
		});` 
Seems like the default is 1 now. 

You might want to specify inputs / outputs too, just in case it changes.. `{ 
inputChannelCount: [1],
			outputChannelCount: [2],
			numberOfInputs: 1,
			numberOfOutputs: 1 }`

Not a bug with DattorroReverbNode, but might want to update the readme @khoin

**Comment by khoin** [comment]
Hi @rikard-io ,
perfect! @padenot used exactly what you said there in his PR ( https://github.com/khoin/DattorroReverbNode/pull/3/commits/caa68215966e395f7f33207f007dee5f794140d9 )

I was under the assumption that @Catsvilles was following the same example. I'll add that to the README.

@Catsvilles Let me know if this resolves your problem or is it something different.

Best,

**Comment by Catsvilles** [comment]
@khoin Nope, cannot manage to make it work, after digging through I think the main problem in my case is connecting it directly to `offlineCtx.destination` rather than creating a new gainNode? Setting the parameters seems to be the right way to fix this right now, but I couldn't manage to make it work. Seems like `outputChannelCount` is always 1 even thought I explicitly specify it to be 2. While playing around with parameters or trying to match them with my destination I managed to invoke this error:

> DOMException: Failed to construct 'AudioWorkletNode': AudioWorkletNode cannot be created: Length of specified 'outputChannelCount' (1) does not match the given number of outputs (0).

Even though I specified outputChannelCount to be 2. Most likely I'm doing something wrong, and if setting options when creating new AudioWorklet works for others I guess issue can be closed. :)

**Comment by khoin** [comment]
@Catsvilles Can you try out the latest version and see if that works?

I tested it on both Mozilla Firefox and Google Chrome, both latest, and they sound/work fine.

I also modified it so it would account for different input-channel counts and behave correctly; i.e.,:

If 2 channels → downmix to 1-channel and process.
If over zero channel (i.e., having at least one-channel input) → copy the first channel to 2nd and process.
Otherwise, feed in silence.

**Comment by khoin** [comment]
@rikard-io 
I've updated the README.md so that it reads:
`new AudioWorkletNode(waContext, 'DattorroReverb', { outputChannelCount: [2] });`
as you said. 

No need to specify input channel count since I've accounted for all the cases in the Processor.
I also don't see why numberOfInputs need to be specified concretely as 1, now that I've accounted for all cases....

The only way I could see a bug being thrown now is line 181 https://github.com/khoin/DattorroReverbNode/blob/bb9c2f21049e189aaa66e3a2c540178036a5ef52/dattorroReverb.js#L181
where `inputs[0]` is undefined

**Comment by Catsvilles** [comment]
@khoin Sorry, took me a while to go back to older project and test this. Yes, with latest version it works perfect, no errors when using it in the loop! + little bonus for people who may find this - tone.js has now addAudioWorkletModule() method which makes working with AudioWorklets super smooth!

I guess I'm closing this, but I have a new question now, regarding the SuperCollider version of this reverb. I just got started with SC and recently found your SC implementation of Dattorro's reverb in sclang [here](https://github.com/khoin/dx463-final) probably I don't understand many things and how SC works yet, but I think that SC implementation is not full or something? At least I couldn't find a way to control that many params, for examples, we cannot change Dry/Wet values? I cannot get a such a deep sounding reverb as with AudioWorklet's version but one thing for sure SC version is much easier on CPU. Would it be possible to make SC version as feature full as JS one? Really would love to have this cool reverb in my SC gear! Thank you!

**Comment by khoin** [comment]
@Catsvilles Hey there. I have no other way to communicate with you so I'll just respond here.
My SC implementation of the reverb (which is 2 years old now) is **not** a faithful one. When I looked at the code again today, I notice some things that you rightly pointed out:
* **Missing (4) diffusion parameters for pre-tank and in-tank allpasses (regarding your comment on "not full").** This is because I did not bother to reverse from `delaytime` and `decaytime` of `AllpassC` (SuperCollider) back to the `k` value of the mathematical description of the allpass (which the Dattorro paper follows). You can work it out. ;)
* **No (or incorrect) tap points/way-of-tapping, which does not corresponds to the correct tap positions in the original paper.** This is because I do not know how to access taps within `DelayC` at the time. I still don't. A quick look up reveals to me that there exists `Tap` and `MultiTap` UGen, which might help "achieve" this. I say "achieve" because it's really a workaround: Tap does not allow for modulation (which the paper asks for "excursion"), MultiTap requires buffers to be provided whereas `DelayC` doesn't. Certainly I can get the right tap points by splitting up into multiple `DelayC`s, but that would just be ridiculous (but I'm sure it is a write-one-use-many sort of thing). If you need an explanation for my code (for example, [line 255](https://github.com/khoin/dx463-final/blob/master/sdefs.sc#L255)), I'm essentially delaying an incoming signal before _a delay_, instead of tapping within _that delay_. This uses more memory.
* **Mix instead of Dry/Wet**. This was simply how I designed it back then. It was not a good choice to complement dry and wet together; that was my lack of judgment. You can simply add these parameters without a hassle. 

The current Dattorro implemention in this (Javascript) repo is even "fuller" in terms of components when compared to the SuperCollider verison. It has two out-of-phase excursions, instead of the same phase for both excursions.

Regarding a fuller SC version.... I don't have the availability to implement such thing at the moment. I would also rather make a UGen or a Quark at this point, instead of a SynthDef. I'm not currently considering diving into SuperCollider.

I hope this helps. And feel free to reach out to me.
