### ISSUE TITLE
Cheaper than Convolver? 

### ISSUE THREAD

**Issue by weepy** [khoin/DattorroReverbNode#8]
Heya - awesome project! Amazed how short the code is !

In you experience is this faster to process than a ConvolverNode with an impulse?

**Comment by khoin** [comment]
Hey there,

Someone would have to do the profiling for that. Especially if the Fourier
Transform is implemented in a certain way, sometimes it can be quite fast.

On the other hand, you’d have to consider the different usages/needs. For
algorithm reverbs such as this one, the “pros” include: flexibility (you
can change the parameters on the fly), modularity (you can reuse components
or add components within the algorithm), etc.

For convolving reverbs, you get more realistic reverbs / more realism —
since the impulses are usually made from impulses of real life spaces, but
it’s more expensive or finnicky to change the reverb on the fly.

K.

**Comment by weepy** [comment]
Yes - I totally understand. It's great that it can be tweaked to your
heart's content. Ofc it scales linearly with the total convolution length
too.

^_^

**Comment by khoin** [comment]
Cool :) have fun!
